// GENERATED by _Kit\sync-kit.ps1 - do not edit by hand.
// Re-run:  .\sync-kit.ps1 -Project Template
//
// Lists only the namespaces this project owns. Adding a namespace means
// adding the folder under i18n\ and re-running the sync.

import faAccountActivity from '@/i18n/account-activity/fa.json';
import enAccountActivity from '@/i18n/account-activity/en.json';
import faAccountApiKeys from '@/i18n/account-api-keys/fa.json';
import enAccountApiKeys from '@/i18n/account-api-keys/en.json';
import faAccountAppearance from '@/i18n/account-appearance/fa.json';
import enAccountAppearance from '@/i18n/account-appearance/en.json';
import faAccountBilling from '@/i18n/account-billing/fa.json';
import enAccountBilling from '@/i18n/account-billing/en.json';
import faAccountHome from '@/i18n/account-home/fa.json';
import enAccountHome from '@/i18n/account-home/en.json';
import faAccountIntegrations from '@/i18n/account-integrations/fa.json';
import enAccountIntegrations from '@/i18n/account-integrations/en.json';
import faAccountInviteAFriend from '@/i18n/account-invite-a-friend/fa.json';
import enAccountInviteAFriend from '@/i18n/account-invite-a-friend/en.json';
import faAccountMembers from '@/i18n/account-members/fa.json';
import enAccountMembers from '@/i18n/account-members/en.json';
import faAccountNotifications from '@/i18n/account-notifications/fa.json';
import enAccountNotifications from '@/i18n/account-notifications/en.json';
import faAccountSecurity from '@/i18n/account-security/fa.json';
import enAccountSecurity from '@/i18n/account-security/en.json';
import faBrokeragesCommon from '@/i18n/brokerages-common/fa.json';
import enBrokeragesCommon from '@/i18n/brokerages-common/en.json';
import faCompanyDocument from '@/i18n/company-document/fa.json';
import enCompanyDocument from '@/i18n/company-document/en.json';
import faCompanyInformation from '@/i18n/company-information/fa.json';
import enCompanyInformation from '@/i18n/company-information/en.json';
import faCompanyInformationGuide from '@/i18n/company-information-guide/fa.json';
import enCompanyInformationGuide from '@/i18n/company-information-guide/en.json';
import faPersonAccess from '@/i18n/person-access/fa.json';
import enPersonAccess from '@/i18n/person-access/en.json';
import faPersonAddress from '@/i18n/person-address/fa.json';
import enPersonAddress from '@/i18n/person-address/en.json';
import faPersonAsset from '@/i18n/person-asset/fa.json';
import enPersonAsset from '@/i18n/person-asset/en.json';
import faPersonContact from '@/i18n/person-contact/fa.json';
import enPersonContact from '@/i18n/person-contact/en.json';
import faPersonDocument from '@/i18n/person-document/fa.json';
import enPersonDocument from '@/i18n/person-document/en.json';
import faPersonEducation from '@/i18n/person-education/fa.json';
import enPersonEducation from '@/i18n/person-education/en.json';
import faPersonEmployment from '@/i18n/person-employment/fa.json';
import enPersonEmployment from '@/i18n/person-employment/en.json';
import faPersonForm from '@/i18n/person-form/fa.json';
import enPersonForm from '@/i18n/person-form/en.json';
import faPersonNameGrid from '@/i18n/person-name-grid/fa.json';
import enPersonNameGrid from '@/i18n/person-name-grid/en.json';
import faPersonNationality from '@/i18n/person-nationality/fa.json';
import enPersonNationality from '@/i18n/person-nationality/en.json';
import faPersonProfessionalTraining from '@/i18n/person-professional-training/fa.json';
import enPersonProfessionalTraining from '@/i18n/person-professional-training/en.json';
import faPersonRelationship from '@/i18n/person-relationship/fa.json';
import enPersonRelationship from '@/i18n/person-relationship/en.json';
import faPersonSearch from '@/i18n/person-search/fa.json';
import enPersonSearch from '@/i18n/person-search/en.json';
import faPersonSidebar from '@/i18n/person-sidebar/fa.json';
import enPersonSidebar from '@/i18n/person-sidebar/en.json';
import faPersonStatus from '@/i18n/person-status/fa.json';
import enPersonStatus from '@/i18n/person-status/en.json';
import faUserManagement from '@/i18n/user-management/fa.json';
import enUserManagement from '@/i18n/user-management/en.json';

export const DOMAIN_NAMESPACES = {
  fa: {
  'account-activity': faAccountActivity,
  'account-api-keys': faAccountApiKeys,
  'account-appearance': faAccountAppearance,
  'account-billing': faAccountBilling,
  'account-home': faAccountHome,
  'account-integrations': faAccountIntegrations,
  'account-invite-a-friend': faAccountInviteAFriend,
  'account-members': faAccountMembers,
  'account-notifications': faAccountNotifications,
  'account-security': faAccountSecurity,
  'brokerages-common': faBrokeragesCommon,
  'company-document': faCompanyDocument,
  'company-information': faCompanyInformation,
  'company-information-guide': faCompanyInformationGuide,
  'person-access': faPersonAccess,
  'person-address': faPersonAddress,
  'person-asset': faPersonAsset,
  'person-contact': faPersonContact,
  'person-document': faPersonDocument,
  'person-education': faPersonEducation,
  'person-employment': faPersonEmployment,
  'person-form': faPersonForm,
  'person-name-grid': faPersonNameGrid,
  'person-nationality': faPersonNationality,
  'person-professional-training': faPersonProfessionalTraining,
  'person-relationship': faPersonRelationship,
  'person-search': faPersonSearch,
  'person-sidebar': faPersonSidebar,
  'person-status': faPersonStatus,
  'user-management': faUserManagement,
  },
  en: {
  'account-activity': enAccountActivity,
  'account-api-keys': enAccountApiKeys,
  'account-appearance': enAccountAppearance,
  'account-billing': enAccountBilling,
  'account-home': enAccountHome,
  'account-integrations': enAccountIntegrations,
  'account-invite-a-friend': enAccountInviteAFriend,
  'account-members': enAccountMembers,
  'account-notifications': enAccountNotifications,
  'account-security': enAccountSecurity,
  'brokerages-common': enBrokeragesCommon,
  'company-document': enCompanyDocument,
  'company-information': enCompanyInformation,
  'company-information-guide': enCompanyInformationGuide,
  'person-access': enPersonAccess,
  'person-address': enPersonAddress,
  'person-asset': enPersonAsset,
  'person-contact': enPersonContact,
  'person-document': enPersonDocument,
  'person-education': enPersonEducation,
  'person-employment': enPersonEmployment,
  'person-form': enPersonForm,
  'person-name-grid': enPersonNameGrid,
  'person-nationality': enPersonNationality,
  'person-professional-training': enPersonProfessionalTraining,
  'person-relationship': enPersonRelationship,
  'person-search': enPersonSearch,
  'person-sidebar': enPersonSidebar,
  'person-status': enPersonStatus,
  'user-management': enUserManagement,
  },
} as const;
